use std::sync::atomic::AtomicBool;
use std::sync::Arc;
use std::time::Duration;

use base64::{engine::general_purpose::STANDARD as B64, Engine};
use russh::client::Handle;

use super::host_key::ClientHandler;
use super::ops::exec_on;
/// Remote shell-integration bootstrap (OSC 7 + OSC 133 hooks for bash/zsh).
/// Staged into a private remote temp file over an exec channel, then sourced
/// by one SHORT line typed into the interactive shell (see
/// `stage_remote_bootstrap` for why it must never be sent inline).
const REMOTE_INTEGRATION: &str = include_str!("../scripts/remote-integration.sh");

const AGENT_HOOK_HELPER: &str = include_str!("../../agent/scripts/agent-hook.sh");

/// Stage the shell-integration bootstrap into a private remote temp file via a
/// one-shot exec channel, returning the remote path to source.
///
/// The script must NEVER be typed into the interactive shell inline: input
/// that arrives before the shell's line editor switches the pty to raw mode
/// sits in the tty's canonical line buffer, which caps a single line at 4096
/// bytes on Linux (1024 on BSD/macOS). The previous one-line
/// `eval "$(printf %s <base64> | base64 -d ...)"` injection was ~11 KB, so the
/// line discipline discarded its tail INCLUDING the terminating newline — the
/// eval never ran, integration was silently lost, and up to 4 KB of base64 was
/// echoed and left pending on the first prompt (junk the user had to Ctrl+C
/// away). The exec channel has no tty, so it carries the payload without any
/// length limit or echo; the shell only ever sees the short source line built
/// by `integration_source_line` (guarded well under the 1024-byte floor).
///
/// `mktemp` creates the file 0600 with O_EXCL under a random name, so a
/// co-tenant on the remote host can neither pre-plant a symlink nor read the
/// staged script. The `sh -c` wrapper keeps the command portable when the
/// login shell is fish/csh. Degrades with Err on servers without
/// mktemp/base64 or with exec disabled; the caller can still attempt a bounded
/// direct cwd restore.
pub(crate) async fn stage_remote_bootstrap(
    handle: &Arc<Handle<ClientHandler>>,
    session_id: &str,
    inject_shell_integration: bool,
    initial_cwd: Option<&str>,
    cancelled: Option<&AtomicBool>,
) -> Result<String, String> {
    let script = render_remote_bootstrap(session_id, inject_shell_integration, initial_cwd);
    let encoded = B64.encode(script.as_bytes());
    let command = integration_stage_command(&encoded);
    let out = exec_on(
        handle.clone(),
        &command,
        4096,
        Duration::from_secs(5),
        false,
        cancelled,
        None,
    )
    .await?;
    // Some servers print a banner/MOTD even on exec channels; take the last
    // line that looks like our mktemp path instead of requiring clean output.
    let path = out
        .lines()
        .map(str::trim)
        .rfind(|line| is_safe_remote_path(line));
    match path {
        Some(path) => Ok(path.to_string()),
        None => Err(format!("unexpected staging output: {:?}", out.trim())),
    }
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}

fn safe_session_id(session_id: &str) -> String {
    session_id
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_'))
        .collect()
}

fn bootstrap_completion_token(session_id: &str) -> String {
    format!("tunara-bootstrap;{}", safe_session_id(session_id))
}

pub(crate) fn bootstrap_completion_marker(session_id: &str) -> Vec<u8> {
    format!("\x1b]777;{}\x1b\\", bootstrap_completion_token(session_id)).into_bytes()
}

fn bootstrap_completion_command(session_id: &str) -> String {
    format!(
        "printf '\\033]777;{}\\033\\\\'",
        bootstrap_completion_token(session_id)
    )
}

fn render_remote_bootstrap(
    session_id: &str,
    inject_shell_integration: bool,
    initial_cwd: Option<&str>,
) -> String {
    // The output pump removes this private marker together with every tty echo
    // of the typed source line. Unlike relative cursor erasure, filtering the
    // exact generated bytes is independent of MOTD, prompt, and readline order.
    let mut script = format!("{}\n", bootstrap_completion_command(session_id));
    if inject_shell_integration {
        script.push_str(&render_remote_integration(session_id));
    }
    if let Some(cwd) = initial_cwd {
        if !script.is_empty() && !script.ends_with('\n') {
            script.push('\n');
        }
        let quoted = shell_quote(cwd);
        script.push_str(&format!(
            "if [ -d {quoted} ]; then\n  cd {quoted} || printf '%s%s\\n' '[tunara] saved remote directory unavailable: ' {quoted}\nelse\n  printf '%s%s\\n' '[tunara] saved remote directory unavailable: ' {quoted}\nfi\n"
        ));
    }
    script
}

fn render_remote_integration(session_id: &str) -> String {
    // Only safe ASCII session ids reach here (logical ids are uuids), but
    // defend against a stray quote breaking the shell by stripping anything
    // outside the id charset before substitution. An empty id disables the
    // agent wrappers via the script's own `[ -n ... ]` guard, leaving
    // OSC 7 / 133 intact.
    let safe_sid = safe_session_id(session_id);
    REMOTE_INTEGRATION
        .replace("__TUNARA_SESSION_ID__", &safe_sid)
        .replace("__TUNARA_AGENT_HOOK_B64__", &B64.encode(AGENT_HOOK_HELPER))
}

/// One-shot exec command that writes the base64 payload to a fresh `mktemp`
/// file and prints the path (and nothing else) on success. Tries the GNU then
/// BSD base64 decode flag; stderr is discarded so failures stay quiet.
fn integration_stage_command(encoded: &str) -> String {
    format!(
        "sh -c 'f=$(mktemp /tmp/.t-XXXXXXXXXX) && {{ printf %s {encoded} | base64 --decode 2>/dev/null || printf %s {encoded} | base64 -D 2>/dev/null; }} > \"$f\" && printf %s \"$f\"'"
    )
}

/// The ONLY line typed into the interactive shell: source the staged file,
/// then remove it. The path is unquoted only because `is_safe_remote_path`
/// restricts it to a shell-inert ASCII charset. Leading space keeps it out of
/// ignorespace-style history. Must stay far below 1024 bytes, the smallest
/// (BSD) canonical-mode tty line buffer. The output pump suppresses the
/// generated command until its completion marker arrives, including both the
/// tty's initial echo and any later (possibly line-wrapped) readline redraw,
/// together with the prompt line that carried it.
pub(crate) fn integration_source_line(path: &str) -> String {
    format!(" . {path};rm -f {path}\n")
}

pub(crate) fn initial_cwd_fallback_line(cwd: &str, session_id: &str) -> String {
    let completion = bootstrap_completion_command(session_id);
    let line = format!(" {completion};cd {}\n", shell_quote(cwd));
    if line.len() < 1_024 {
        line
    } else {
        format!(
            " {completion};printf '%s\\n' '[tunara] saved remote directory path is too long to restore'\n"
        )
    }
}

/// Accept only the path shape our own stage command can produce — an absolute
/// `/tmp/.t-*` path in a conservative charset. Anything else (error
/// text, MOTD noise, a hostile multi-line blob) must not reach the shell line.
fn is_safe_remote_path(path: &str) -> bool {
    path.starts_with("/tmp/.t-")
        && path.len() < 200
        && path
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '/' | '.' | '_' | '-'))
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn source_line_fits_every_canonical_tty_buffer() {
        let line = integration_source_line("/tmp/.t-AbCd012345");
        assert!(
            line.len() < 256,
            "shell line too long: {} bytes",
            line.len()
        );
        assert!(line.ends_with('\n'));
        assert_eq!(line.matches('\n').count(), 1, "must be a single line");
        assert!(
            line.starts_with(' '),
            "leading space keeps it out of history"
        );
        assert!(
            line.len() < 64,
            "source command must stay on one typical prompt line"
        );
    }

    /// The full bootstrap payload (script + base64 expansion) must never leak
    /// into the shell line — only into the exec-channel stage command.
    #[test]
    fn payload_travels_on_the_exec_channel_only() {
        let rendered = render_remote_integration("session-1'$(id)");
        assert!(!rendered.contains("__TUNARA_SESSION_ID__"));
        assert!(!rendered.contains("__TUNARA_AGENT_HOOK_B64__"));
        assert!(rendered.contains("session-1id"));
        assert!(rendered.contains(&B64.encode(AGENT_HOOK_HELPER)[..32]));
        let encoded = B64.encode(rendered.as_bytes());
        assert!(
            encoded.len() > 4096,
            "payload no longer exceeds the canonical limit; if this shrank on \
         purpose the staging design still stands, update this bound"
        );
        let stage = integration_stage_command(&encoded);
        assert!(stage.contains(&encoded));
        let line = integration_source_line("/tmp/.t-AbCd012345");
        assert!(!line.contains(&encoded[..32]));
    }

    #[test]
    fn remote_bootstrap_restores_a_shell_quoted_unicode_cwd() {
        let cwd = "/srv/可爱动物/it's-here";
        let rendered = render_remote_bootstrap("session-1", true, Some(cwd));
        assert!(rendered.starts_with("printf '\\033]777;tunara-bootstrap;session-1\\033\\\\'\n"));
        assert_eq!(
            bootstrap_completion_marker("session-1"),
            b"\x1b]777;tunara-bootstrap;session-1\x1b\\"
        );
        assert!(rendered.contains("cd '/srv/可爱动物/it'\"'\"'s-here'"));
        assert!(rendered.contains("saved remote directory unavailable"));
        assert!(rendered.contains("session-1"));
        let line = integration_source_line("/tmp/.t-AbCd012345");
        assert!(!line.contains(cwd), "cwd stays in the staged payload");
    }

    #[test]
    fn cwd_only_bootstrap_does_not_install_shell_integration() {
        let rendered = render_remote_bootstrap("session-1", false, Some("/srv/app"));
        assert!(rendered.contains("cd '/srv/app'"));
        assert!(!rendered.contains("__tunara_"));
    }

    #[test]
    fn initial_cwd_fallback_is_tty_bounded() {
        assert_eq!(
            initial_cwd_fallback_line("/srv/my app", "session-1"),
            " printf '\\033]777;tunara-bootstrap;session-1\\033\\\\';cd '/srv/my app'\n"
        );
        let long = format!("/{}", "'".repeat(4_096));
        let line = initial_cwd_fallback_line(&long, "session-1");
        assert!(line.len() < 1_024);
        assert!(line.contains("too long"));
    }

    #[test]
    fn stage_output_path_is_validated() {
        assert!(is_safe_remote_path("/tmp/.t-aB3xY9_qWe"));
        // Error text, prompts, or anything shell-active must be rejected.
        assert!(!is_safe_remote_path(""));
        assert!(!is_safe_remote_path("mktemp: not found"));
        assert!(!is_safe_remote_path("/tmp/.t-x; rm -rf ~"));
        assert!(!is_safe_remote_path("/tmp/.t-x\n/etc/passwd"));
        assert!(!is_safe_remote_path("/tmp/evil-si-abc"));
        assert!(!is_safe_remote_path("/tmp/.t-x y"));
        assert!(!is_safe_remote_path("/tmp/.t-x\"$(id)\""));
    }
}
